### ISSUE TITLE
Use of tailwind and selecting text gives an issue

### ISSUE THREAD

**Issue by bovandersteene** [GhentCDH/vue_component_annotated_text#17]
**Is your feature request related to a problem? Please describe.** 
Applied this in f.e. a project with tailwind then there is a border everywhere when trying to select text.
![image](https://github.com/user-attachments/assets/88459384-c59c-4936-9057-52d3cc131357)

**Describe the solution you'd like**
Prefix all css classes in the component with `ann` or something unique

**Comment by bovandersteene** [comment]
Proposed solution 

```markdown
## Discussion on Border Styling Issue with Tailwind

The issue we're encountering isn't directly related to our implementation but rather to how Tailwind (and similar frameworks) handle default CSS properties. Specifically, the following CSS rule affects all elements:

```scss
*, ::before, ::after {
    box-sizing: border-box;
    border-width: 0;
    border-style: solid;
    border-color: #e5e7eb;
}
```

To address this, we can explicitly set the `border-style` to `none` for specific borders in our CSS. Below is a mixin solution that allows us to define which borders to show or hide.

### Proposed Solution: Mixin for Border Styles

We can create a mixin called `show-border` that accepts a list of borders to apply. The mixin applies Tailwind classes and overrides the border styles as needed.

```scss
@mixin show-border($borders: ()) {
    @apply border-2 border-x-0 border-y-0 border-success;

    @if index($borders, 'top') {
        border-top-style: solid;
        @apply border-t-2;
    } @else {
        border-top-style: none;
    } 
    
    @if index($borders, 'bottom') {
        border-bottom-style: solid;
        @apply border-b-2;
    } @else {
        border-bottom-style: none;
    }
    
    @if index($borders, 'left') {
        border-left-style: solid;
        @apply border-l-2;
    } @else {
        border-left-style: none;
    }
    
    @if index($borders, 'right') {
        border-right-style: solid;
        @apply border-r-2;
    } @else {
        border-right-style: none;
    }
}
```

### Applying the Mixin

We can use this mixin within our annotations as follows:

```scss
.annotation--rule-applied {
    &.annotation--start::before {
        @include show-border(('top', 'bottom', 'left'));
    }

    &.annotation--end::before {
        @include show-border(('top', 'bottom', 'right'));
    }
    
    &::before {
        @include show-border(('top', 'bottom'));
    }
}
```

### Summary

By implementing the `show-border` mixin, we can effectively manage the border styles applied to our components while working within the constraints of Tailwind's default styles. This allows for greater flexibility and control over how borders are displayed in our application.
```
