### ISSUE TITLE
Use css variables to overwrite colors and others

### ISSUE THREAD

**Issue by bovandersteene** [GhentCDH/vue_component_annotated_text#18]
**Is your feature request related to a problem? Please describe.**
It makes it easier to overwrite some colors, instead of overwriting classes we can use different variables.
Even if we reuse the component on multiple places then the variable can be overwritten with different colors

**Example**
It can be done on root level

```scss
:root {
  --main-bg-color: brown;
}
``` 

but also on lower level
```scss
section {
  --main-bg-color: red;
}
```
In this example every main bg color will be brown, except when defined in a section there it will be red!

**Additional context**
[Using CSS custom properties (variables)](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties).](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)
